### ISSUE TITLE
Vizumap not working: Dependencies retired

### ISSUE THREAD

**Issue by merel-52n** [lydialucchesi/Vizumap#8]
Hi, I'm not sure if you're aware, but currently Vizumap will not work any more because some libraries (rgeos, maptools) retired that Vizumap is dependent on. See https://cran.r-project.org/web/packages/sp/vignettes/retiring_rgdal_geos_1.html

**Comment by lydialucchesi** [comment]
Hi @merel-52n, thanks for raising this issue. We will look into it. Best, Lydia

**Comment by edzer** [comment]
Let me know if you need any help on this!

**Comment by pkuhnert** [comment]
Hi Edzer,  Lydia was going to look into this but she has since moved back to the USA.  Let me have a look today.  This was on our radar to fix.  As I'm giving a tutorial next week I need to get this sorted as a priority.  I'll let you know how I go.  Thanks for your patience.
Cheers Petra

**Comment by lydialucchesi** [comment]
Dear @merel-52n and @edzer,

Thank you for your attention to this issue. I apologize for the delay in addressing it.

The pixelate function required the geoaxe and rgeos packages, which have both been archived. In turn, I have just rewritten the pixelate function and updated the docs. If you use the new pixelate function, please let me know if you run into any issues or have concerns!

Again, many thanks @merel-52n for opening the issue and @edzer for your offer to help.

Kind regards,
Lydia

**Comment by edzer** [comment]
Thanks, I can confirm that installation works without having rgeos installed.

**Comment by edzer** [comment]
Next project maybe being moving entirely from `sp` to `sf` classes?
